version: '2'

services:
  db:
    restart: always
    image: "sameersbn/postgresql:9.5-1"
    environment:
      - "DB_NAME=acception"
      - "PG_PASSWORD=postgres"
    expose:
      - "5440"
    ports:
      - "5440:5432"
    volumes:
      - db-volume-acception:/var/lib/postgres/9.5/main

volumes:
  db-volume-acception:
